import { HUMAN_BODY_MAPPER } from "../constants";
import { processData } from "../bodyplotSlice";
import {
  receivedBodyplotData,
  expectedProcessedData,
} from "./bodyplotSlice.test.data";

describe("test processData for Bodyplot response", () => {
  test("processData", () => {
    const results = processData(
      receivedBodyplotData.data.viewer.repository.cases.aggregations
        .diagnoses__tissue_or_organ_of_origin.buckets,
      receivedBodyplotData.data.viewer.repository.files.aggregations
        .cases__diagnoses__tissue_or_organ_of_origin.buckets,
    );
    expect(results).toEqual(expectedProcessedData);
  });
});

describe("test indexing human body mapper", () => {
  test("indexing human body mapper byPrimarySite", () => {
    expect(HUMAN_BODY_MAPPER("byPrimarySite")).toEqual({
      "accessory sinuses": "Head and Neck",
      "adrenal gland": "Adrenal Gland",
      "anus and anal canal": "Other and Ill-defined Sites",
      "base of tongue": "Head and Neck",
      bladder: "Bladder",
      "bones, joints and articular cartilage of limbs": "Bone",
      "bones, joints and articular cartilage of other and unspecified sites":
        "Bone",
      brain: "Brain",
      breast: "Breast",
      "bronchus and lung": "Lung",
      "cervix uteri": "Cervix",
      colon: "Colorectal",
      "connective, subcutaneous and other soft tissues": "Soft Tissue",
      "corpus uteri": "Uterus",
      esophagus: "Esophagus",
      "eye and adnexa": "Eye",
      "floor of mouth": "Head and Neck",
      gallbladder: "Other and Ill-defined Sites",
      gum: "Head and Neck",
      "heart, mediastinum, and pleura": "Pleura",
      "hematopoietic and reticuloendothelial systems": "Bone Marrow and Blood",
      hypopharynx: "Head and Neck",
      kidney: "Kidney",
      larynx: "Head and Neck",
      lip: "Head and Neck",
      "liver and intrahepatic bile ducts": "Liver",
      "lymph nodes": "Lymph Nodes",
      meninges: "Nervous System",
      "nasal cavity and middle ear": "Head and Neck",
      nasopharynx: "Head and Neck",
      "not reported": "Not Reported",
      oropharynx: "Head and Neck",
      "other and ill-defined digestive organs": "Other and Ill-defined Sites",
      "other and ill-defined sites": "Other and Ill-defined Sites",
      "other and ill-defined sites in lip, oral cavity and pharynx":
        "Head and Neck",
      "other and ill-defined sites within respiratory system and intrathoracic organs":
        "Other and Ill-defined Sites",
      "other and unspecified female genital organs":
        "Other and Ill-defined Sites",
      "other and unspecified major salivary glands": "Head and Neck",
      "other and unspecified male genital organs":
        "Other and Ill-defined Sites",
      "other and unspecified parts of biliary tract": "Bile Duct",
      "other and unspecified parts of mouth": "Head and Neck",
      "other and unspecified parts of tongue": "Head and Neck",
      "other and unspecified urinary organs": "Other and Ill-defined Sites",
      "other endocrine glands and related structures":
        "Other and Ill-defined Sites",
      ovary: "Ovary",
      palate: "Head and Neck",
      pancreas: "Pancreas",
      "parotid gland": "Head and Neck",
      penis: "Other and Ill-defined Sites",
      "peripheral nerves and autonomic nervous system": "Nervous System",
      placenta: "Other and Ill-defined Sites",
      "prostate gland": "Prostate",
      "pyriform sinus": "Head and Neck",
      "rectosigmoid junction": "Colorectal",
      rectum: "Colorectal",
      "renal pelvis": "Other and Ill-defined Sites",
      "retroperitoneum and peritoneum": "Other and Ill-defined Sites",
      skin: "Skin",
      "small intestine": "Stomach",
      "spinal cord, cranial nerves, and other parts of central nervous system":
        "Nervous System",
      stomach: "Stomach",
      testis: "Testis",
      thymus: "Thymus",
      "thyroid gland": "Thyroid",
      tonsil: "Head and Neck",
      trachea: "Head and Neck",
      unknown: "Not Reported",
      "unknown primary site": "Other and Ill-defined Sites",
      ureter: "Other and Ill-defined Sites",
      "uterus, nos": "Uterus",
      vagina: "Other and Ill-defined Sites",
      vulva: "Other and Ill-defined Sites",
    });
  });

  test("indexing human body mapper byTissueOrOrganOfOrigin", () => {
    expect(HUMAN_BODY_MAPPER("byTissueOrOrganOfOrigin")).toEqual({
      "abdomen, nos": "Other and Ill-defined Sites",
      "abdominal esophagus": "Esophagus",
      "accessory sinus, nos": "Head and Neck",
      "acoustic nerve": "Nervous System",
      "adrenal gland, nos": "Adrenal Gland",
      "ampulla of vater": "Bile Duct",
      "anal canal": "Other and Ill-defined Sites",
      "anterior 2/3 of tongue, nos": "Head and Neck",
      "anterior floor of mouth": "Head and Neck",
      "anterior mediastinum": "Pleura",
      "anterior surface of epiglottis": "Head and Neck",
      "anterior wall of bladder": "Bladder",
      "anterior wall of nasopharynx": "Head and Neck",
      "anus, nos": "Other and Ill-defined Sites",
      "aortic body and other paraganglia": "Other and Ill-defined Sites",
      appendix: "Colorectal",
      "ascending colon": "Colorectal",
      "autonomic nervous system, nos": "Nervous System",
      "axillary tail of breast": "Breast",
      "base of tongue, nos": "Head and Neck",
      "biliary tract, nos": "Bile Duct",
      "bladder neck": "Bladder",
      "bladder, nos": "Bladder",
      blood: "Bone Marrow and Blood",
      "body of pancreas": "Pancreas",
      "body of penis": "Other and Ill-defined Sites",
      "body of stomach": "Stomach",
      "bone marrow": "Bone Marrow and Blood",
      "bone of limb, nos": "Bone",
      "bone, nos": "Bone",
      "bones of skull and face and associated joints": "Bone",
      "border of tongue": "Head and Neck",
      "brain stem": "Brain",
      "brain, nos": "Brain",
      "branchial cleft": "Head and Neck",
      "breast, nos": "Breast",
      "broad ligament": "Other and Ill-defined Sites",
      "cardia, nos": "Stomach",
      "carotid body": "Other and Ill-defined Sites",
      "cauda equina": "Nervous System",
      cecum: "Colorectal",
      "central portion of breast": "Breast",
      "cerebellum, nos": "Brain",
      "cerebral meninges": "Nervous System",
      cerebrum: "Brain",
      "cervical esophagus": "Esophagus",
      "cervix uteri": "Cervix",
      "cheek mucosa": "Head and Neck",
      choroid: "Eye",
      "ciliary body": "Eye",
      clitoris: "Other and Ill-defined Sites",
      "cloacogenic zone": "Other and Ill-defined Sites",
      "colon, nos": "Colorectal",
      "commissure of lip": "Head and Neck",
      conjunctiva: "Eye",
      "connective, subcutaneous and other soft tissues of abdomen":
        "Soft Tissue",
      "connective, subcutaneous and other soft tissues of head, face, and neck":
        "Soft Tissue",
      "connective, subcutaneous and other soft tissues of lower limb and hip":
        "Soft Tissue",
      "connective, subcutaneous and other soft tissues of pelvis":
        "Soft Tissue",
      "connective, subcutaneous and other soft tissues of thorax":
        "Soft Tissue",
      "connective, subcutaneous and other soft tissues of trunk, nos":
        "Soft Tissue",
      "connective, subcutaneous and other soft tissues of upper limb and shoulder":
        "Soft Tissue",
      "connective, subcutaneous and other soft tissues, nos": "Soft Tissue",
      "cornea, nos": "Eye",
      "corpus uteri": "Uterus",
      "cortex of adrenal gland": "Adrenal Gland",
      "cranial nerve, nos": "Nervous System",
      "craniopharyngeal duct": "Other and Ill-defined Sites",
      "descended testis": "Testis",
      "descending colon": "Colorectal",
      "dome of bladder": "Bladder",
      "dorsal surface of tongue, nos": "Head and Neck",
      duodenum: "Stomach",
      endocervix: "Cervix",
      "endocrine gland, nos": "Other and Ill-defined Sites",
      endometrium: "Uterus",
      epididymis: "Other and Ill-defined Sites",
      "esophagus, nos": "Esophagus",
      "ethmoid sinus": "Head and Neck",
      exocervix: "Cervix",
      "external ear": "Skin",
      "external lip, nos": "Head and Neck",
      "external lower lip": "Head and Neck",
      "external upper lip": "Head and Neck",
      "extrahepatic bile duct": "Bile Duct",
      "eye, nos": "Eye",
      eyelid: "Skin",
      "fallopian tube": "Other and Ill-defined Sites",
      "female genital tract, nos": "Other and Ill-defined Sites",
      "floor of mouth, nos": "Head and Neck",
      "frontal lobe": "Brain",
      "frontal sinus": "Head and Neck",
      "fundus of stomach": "Stomach",
      "fundus uteri": "Uterus",
      gallbladder: "Other and Ill-defined Sites",
      "gastric antrum": "Stomach",
      "gastrointestinal tract, nos": "Other and Ill-defined Sites",
      "glans penis": "Other and Ill-defined Sites",
      glottis: "Head and Neck",
      "greater curvature of stomach, nos": "Stomach",
      "gum, nos": "Head and Neck",
      "hard palate": "Head and Neck",
      "head of pancreas": "Pancreas",
      "head, face or neck, nos": "Head and Neck",
      heart: "Pleura",
      "hematopoietic system, nos": "Bone Marrow and Blood",
      "hepatic flexure of colon": "Colorectal",
      "hypopharyngeal aspect of aryepiglottic fold": "Head and Neck",
      "hypopharynx, nos": "Head and Neck",
      ileum: "Stomach",
      "ill-defined sites within respiratory system":
        "Other and Ill-defined Sites",
      "intestinal tract, nos": "Other and Ill-defined Sites",
      "intra-abdominal lymph nodes": "Lymph Nodes",
      "intrahepatic bile duct": "Liver",
      "intrathoracic lymph nodes": "Lymph Nodes",
      "islets of langerhans": "Pancreas",
      "isthmus uteri": "Uterus",
      jejunum: "Stomach",
      "kidney, nos": "Kidney",
      "labium majus": "Other and Ill-defined Sites",
      "labium minus": "Other and Ill-defined Sites",
      "lacrimal gland": "Eye",
      "laryngeal cartilage": "Head and Neck",
      "larynx, nos": "Head and Neck",
      "lateral floor of mouth": "Head and Neck",
      "lateral wall of bladder": "Bladder",
      "lateral wall of nasopharynx": "Head and Neck",
      "lateral wall of oropharynx": "Head and Neck",
      "lesser curvature of stomach, nos": "Stomach",
      "lingual tonsil": "Head and Neck",
      "lip, nos": "Head and Neck",
      liver: "Liver",
      "long bones of lower limb and associated joints": "Bone",
      "long bones of upper limb, scapula and associated joints": "Bone",
      "lower gum": "Head and Neck",
      "lower limb, nos": "Other and Ill-defined Sites",
      "lower lobe, lung": "Lung",
      "lower third of esophagus": "Esophagus",
      "lower-inner quadrant of breast": "Breast",
      "lower-outer quadrant of breast": "Breast",
      "lung, nos": "Lung",
      "lymph node, nos": "Lymph Nodes",
      "lymph nodes of axilla or arm": "Lymph Nodes",
      "lymph nodes of head, face and neck": "Lymph Nodes",
      "lymph nodes of inguinal region or leg": "Lymph Nodes",
      "lymph nodes of multiple regions": "Lymph Nodes",
      "main bronchus": "Lung",
      "major salivary gland, nos": "Head and Neck",
      "male genital organs, nos": "Other and Ill-defined Sites",
      mandible: "Bone",
      "maxillary sinus": "Head and Neck",
      "meckel diverticulum": "Stomach",
      "mediastinum, nos": "Pleura",
      "medulla of adrenal gland": "Adrenal Gland",
      "meninges, nos": "Nervous System",
      "middle ear": "Head and Neck",
      "middle lobe, lung": "Lung",
      "middle third of esophagus": "Esophagus",
      "mouth, nos": "Head and Neck",
      "mucosa of lip, nos": "Head and Neck",
      "mucosa of lower lip": "Head and Neck",
      "mucosa of upper lip": "Head and Neck",
      myometrium: "Uterus",
      "nasal cavity": "Head and Neck",
      "nasopharynx, nos": "Head and Neck",
      "nervous system, nos": "Nervous System",
      nipple: "Breast",
      "not reported": "Not Reported",
      "occipital lobe": "Brain",
      "olfactory nerve": "Nervous System",
      "optic nerve": "Nervous System",
      "orbit, nos": "Eye",
      "oropharynx, nos": "Head and Neck",
      "other ill-defined sites": "Other and Ill-defined Sites",
      "other specified parts of female genital organs":
        "Other and Ill-defined Sites",
      "other specified parts of male genital organs":
        "Other and Ill-defined Sites",
      "other specified parts of pancreas": "Pancreas",
      ovary: "Ovary",
      "overlapping lesion of accessory sinuses": "Head and Neck",
      "overlapping lesion of biliary tract": "Bile Duct",
      "overlapping lesion of bladder": "Bladder",
      "overlapping lesion of bones, joints and articular cartilage": "Bone",
      "overlapping lesion of bones, joints and articular cartilage of limbs":
        "Bone",
      "overlapping lesion of brain": "Brain",
      "overlapping lesion of brain and central nervous system":
        "Nervous System",
      "overlapping lesion of breast": "Breast",
      "overlapping lesion of cervix uteri": "Cervix",
      "overlapping lesion of colon": "Colorectal",
      "overlapping lesion of connective, subcutaneous and other soft tissues":
        "Soft Tissue",
      "overlapping lesion of corpus uteri": "Uterus",
      "overlapping lesion of digestive system": "Other and Ill-defined Sites",
      "overlapping lesion of endocrine glands and related structures":
        "Other and Ill-defined Sites",
      "overlapping lesion of esophagus": "Esophagus",
      "overlapping lesion of eye and adnexa": "Eye",
      "overlapping lesion of female genital organs":
        "Other and Ill-defined Sites",
      "overlapping lesion of floor of mouth": "Head and Neck",
      "overlapping lesion of heart, mediastinum and pleura": "Pleura",
      "overlapping lesion of hypopharynx": "Head and Neck",
      "overlapping lesion of ill-defined sites": "Other and Ill-defined Sites",
      "overlapping lesion of larynx": "Head and Neck",
      "overlapping lesion of lip": "Head and Neck",
      "overlapping lesion of lip, oral cavity and pharynx": "Head and Neck",
      "overlapping lesion of lung": "Lung",
      "overlapping lesion of major salivary glands": "Head and Neck",
      "overlapping lesion of male genital organs":
        "Other and Ill-defined Sites",
      "overlapping lesion of nasopharynx": "Head and Neck",
      "overlapping lesion of other and unspecified parts of mouth":
        "Head and Neck",
      "overlapping lesion of palate": "Head and Neck",
      "overlapping lesion of pancreas": "Pancreas",
      "overlapping lesion of penis": "Other and Ill-defined Sites",
      "overlapping lesion of peripheral nerves and autonomic nervous system":
        "Nervous System",
      "overlapping lesion of rectum, anus and anal canal":
        "Other and Ill-defined Sites",
      "overlapping lesion of respiratory system and intrathoracic organs":
        "Other and Ill-defined Sites",
      "overlapping lesion of retroperitoneum and peritoneum":
        "Other and Ill-defined Sites",
      "overlapping lesion of skin": "Skin",
      "overlapping lesion of small intestine": "Stomach",
      "overlapping lesion of stomach": "Stomach",
      "overlapping lesion of tongue": "Head and Neck",
      "overlapping lesion of tonsil": "Head and Neck",
      "overlapping lesion of urinary organs": "Other and Ill-defined Sites",
      "overlapping lesion of vulva": "Other and Ill-defined Sites",
      "overlapping lesions of oropharynx": "Head and Neck",
      "palate, nos": "Head and Neck",
      "pancreas, nos": "Pancreas",
      "pancreatic duct": "Pancreas",
      parametrium: "Other and Ill-defined Sites",
      "parathyroid gland": "Other and Ill-defined Sites",
      "paraurethral gland": "Other and Ill-defined Sites",
      "parietal lobe": "Brain",
      "parotid gland": "Head and Neck",
      "pelvic bones, sacrum, coccyx and associated joints": "Bone",
      "pelvic lymph nodes": "Lymph Nodes",
      "pelvis, nos": "Bone",
      "penis, nos": "Other and Ill-defined Sites",
      "peripheral nerves and autonomic nervous system of abdomen":
        "Nervous System",
      "peripheral nerves and autonomic nervous system of head, face, and neck":
        "Nervous System",
      "peripheral nerves and autonomic nervous system of lower limb and hip":
        "Nervous System",
      "peripheral nerves and autonomic nervous system of pelvis":
        "Nervous System",
      "peripheral nerves and autonomic nervous system of thorax":
        "Nervous System",
      "peripheral nerves and autonomic nervous system of trunk, nos":
        "Nervous System",
      "peripheral nerves and autonomic nervous system of upper limb and shoulder":
        "Nervous System",
      "peritoneum, nos": "Other and Ill-defined Sites",
      "pharynx, nos": "Head and Neck",
      "pineal gland": "Other and Ill-defined Sites",
      "pituitary gland": "Other and Ill-defined Sites",
      placenta: "Other and Ill-defined Sites",
      "pleura, nos": "Pleura",
      "postcricoid region": "Head and Neck",
      "posterior mediastinum": "Pleura",
      "posterior wall of bladder": "Bladder",
      "posterior wall of hypopharynx": "Head and Neck",
      "posterior wall of nasopharynx": "Head and Neck",
      "posterior wall of oropharynx": "Head and Neck",
      prepuce: "Other and Ill-defined Sites",
      "prostate gland": "Prostate",
      pylorus: "Stomach",
      "pyriform sinus": "Head and Neck",
      "rectosigmoid junction": "Colorectal",
      "rectum, nos": "Colorectal",
      "renal pelvis": "Other and Ill-defined Sites",
      "reticuloendothelial system, nos": "Bone Marrow and Blood",
      retina: "Eye",
      "retromolar area": "Head and Neck",
      retroperitoneum: "Other and Ill-defined Sites",
      "rib, sternum, clavicle and associated joints": "Bone",
      "round ligament": "Other and Ill-defined Sites",
      "scrotum, nos": "Other and Ill-defined Sites",
      "short bones of lower limb and associated joints": "Bone",
      "short bones of upper limb and associated joints": "Bone",
      "sigmoid colon": "Colorectal",
      "skin of lip, nos": "Skin",
      "skin of lower limb and hip": "Skin",
      "skin of other and unspecified parts of face": "Skin",
      "skin of scalp and neck": "Skin",
      "skin of trunk": "Skin",
      "skin of upper limb and shoulder": "Skin",
      "skin, nos": "Skin",
      "small intestine, nos": "Stomach",
      "soft palate, nos": "Head and Neck",
      "specified parts of peritoneum": "Other and Ill-defined Sites",
      "spermatic cord": "Other and Ill-defined Sites",
      "sphenoid sinus": "Head and Neck",
      "spinal cord": "Nervous System",
      "spinal meninges": "Nervous System",
      spleen: "Bone Marrow and Blood",
      "splenic flexure of colon": "Colorectal",
      "stomach, nos": "Stomach",
      subglottis: "Head and Neck",
      "sublingual gland": "Head and Neck",
      "submandibular gland": "Head and Neck",
      "superior wall of nasopharynx": "Head and Neck",
      supraglottis: "Head and Neck",
      "tail of pancreas": "Pancreas",
      "temporal lobe": "Brain",
      "testis, nos": "Testis",
      "thoracic esophagus": "Esophagus",
      "thorax, nos": "Other and Ill-defined Sites",
      thymus: "Thymus",
      "thyroid gland": "Thyroid",
      "tongue, nos": "Head and Neck",
      "tonsil, nos": "Head and Neck",
      "tonsillar fossa": "Head and Neck",
      "tonsillar pillar": "Head and Neck",
      trachea: "Head and Neck",
      "transverse colon": "Colorectal",
      "trigone of bladder": "Bladder",
      "undescended testis": "Testis",
      unknown: "Not Reported",
      "unknown primary site": "Other and Ill-defined Sites",
      "upper gum": "Head and Neck",
      "upper limb, nos": "Other and Ill-defined Sites",
      "upper lobe, lung": "Lung",
      "upper respiratory tract, nos": "Other and Ill-defined Sites",
      "upper third of esophagus": "Esophagus",
      "upper-inner quadrant of breast": "Breast",
      "upper-outer quadrant of breast": "Breast",
      urachus: "Bladder",
      ureter: "Other and Ill-defined Sites",
      "ureteric orifice": "Bladder",
      urethra: "Other and Ill-defined Sites",
      "urinary system, nos": "Other and Ill-defined Sites",
      "uterine adnexa": "Other and Ill-defined Sites",
      "uterus, nos": "Uterus",
      uvula: "Head and Neck",
      "vagina, nos": "Other and Ill-defined Sites",
      vallecula: "Head and Neck",
      "ventral surface of tongue, nos": "Head and Neck",
      "ventricle, nos": "Brain",
      "vertebral column": "Bone",
      "vestibule of mouth": "Head and Neck",
      "vulva, nos": "Other and Ill-defined Sites",
      "waldeyer ring": "Head and Neck",
    });
  });
});
