export const receivedBodyplotData = {
  data: {
    viewer: {
      repository: {
        cases: {
          aggregations: {
            primary_site: {
              buckets: [
                {
                  doc_count: 12213,
                  key: "bronchus and lung",
                },
                {
                  doc_count: 9594,
                  key: "hematopoietic and reticuloendothelial systems",
                },
                {
                  doc_count: 9123,
                  key: "breast",
                },
                {
                  doc_count: 6920,
                  key: "colon",
                },
                {
                  doc_count: 3703,
                  key: "spinal cord, cranial nerves, and other parts of central nervous system",
                },
                {
                  doc_count: 3462,
                  key: "kidney",
                },
                {
                  doc_count: 3402,
                  key: "ovary",
                },
                {
                  doc_count: 3233,
                  key: "unknown",
                },
                {
                  doc_count: 2889,
                  key: "skin",
                },
                {
                  doc_count: 2753,
                  key: "pancreas",
                },
                {
                  doc_count: 2391,
                  key: "prostate gland",
                },
                {
                  doc_count: 1898,
                  key: "uterus, nos",
                },
                {
                  doc_count: 1881,
                  key: "thyroid gland",
                },
                {
                  doc_count: 1725,
                  key: "bladder",
                },
                {
                  doc_count: 1611,
                  key: "liver and intrahepatic bile ducts",
                },
                {
                  doc_count: 1574,
                  key: "connective, subcutaneous and other soft tissues",
                },
                {
                  doc_count: 1456,
                  key: "brain",
                },
                {
                  doc_count: 1403,
                  key: "esophagus",
                },
                {
                  doc_count: 1355,
                  key: "stomach",
                },
                {
                  doc_count: 1189,
                  key: "other and ill-defined sites",
                },
                {
                  doc_count: 1109,
                  key: "rectum",
                },
                {
                  doc_count: 915,
                  key: "cervix uteri",
                },
                {
                  doc_count: 851,
                  key: "adrenal gland",
                },
                {
                  doc_count: 792,
                  key: "corpus uteri",
                },
                {
                  doc_count: 720,
                  key: "other and ill-defined digestive organs",
                },
                {
                  doc_count: 706,
                  key: "heart, mediastinum, and pleura",
                },
                {
                  doc_count: 616,
                  key: "other and unspecified major salivary glands",
                },
                {
                  doc_count: 542,
                  key: "testis",
                },
                {
                  doc_count: 538,
                  key: "lymph nodes",
                },
                {
                  doc_count: 456,
                  key: "bones, joints and articular cartilage of other and unspecified sites",
                },
                {
                  doc_count: 418,
                  key: "peripheral nerves and autonomic nervous system",
                },
                {
                  doc_count: 384,
                  key: "retroperitoneum and peritoneum",
                },
                {
                  doc_count: 361,
                  key: "other and ill-defined sites in lip, oral cavity and pharynx",
                },
                {
                  doc_count: 314,
                  key: "not reported",
                },
                {
                  doc_count: 306,
                  key: "thymus",
                },
                {
                  doc_count: 270,
                  key: "small intestine",
                },
                {
                  doc_count: 268,
                  key: "bones, joints and articular cartilage of limbs",
                },
                {
                  doc_count: 265,
                  key: "gallbladder",
                },
                {
                  doc_count: 243,
                  key: "meninges",
                },
                {
                  doc_count: 235,
                  key: "anus and anal canal",
                },
                {
                  doc_count: 227,
                  key: "other and unspecified parts of biliary tract",
                },
                {
                  doc_count: 222,
                  key: "eye and adnexa",
                },
                {
                  doc_count: 217,
                  key: "other and unspecified urinary organs",
                },
                {
                  doc_count: 194,
                  key: "oropharynx",
                },
                {
                  doc_count: 182,
                  key: "other endocrine glands and related structures",
                },
                {
                  doc_count: 169,
                  key: "larynx",
                },
                {
                  doc_count: 163,
                  key: "other and unspecified female genital organs",
                },
                {
                  doc_count: 133,
                  key: "other and unspecified parts of tongue",
                },
                {
                  doc_count: 101,
                  key: "nasopharynx",
                },
                {
                  doc_count: 80,
                  key: "rectosigmoid junction",
                },
                {
                  doc_count: 72,
                  key: "vagina",
                },
                {
                  doc_count: 56,
                  key: "floor of mouth",
                },
                {
                  doc_count: 46,
                  key: "tonsil",
                },
                {
                  doc_count: 43,
                  key: "other and unspecified parts of mouth",
                },
                {
                  doc_count: 40,
                  key: "nasal cavity and middle ear",
                },
                {
                  doc_count: 33,
                  key: "penis",
                },
                {
                  doc_count: 25,
                  key: "hypopharynx",
                },
                {
                  doc_count: 24,
                  key: "base of tongue",
                },
                {
                  doc_count: 15,
                  key: "ureter",
                },
                {
                  doc_count: 11,
                  key: "gum",
                },
                {
                  doc_count: 10,
                  key: "vulva",
                },
                {
                  doc_count: 9,
                  key: "lip",
                },
                {
                  doc_count: 7,
                  key: "trachea",
                },
                {
                  doc_count: 5,
                  key: "palate",
                },
                {
                  doc_count: 2,
                  key: "other and ill-defined sites within respiratory system and intrathoracic organs",
                },
                {
                  doc_count: 1,
                  key: "other and unspecified male genital organs",
                },
                {
                  doc_count: 1,
                  key: "renal pelvis",
                },
              ],
            },
          },
        },
      },
    },
  },
};

export const expectedProcessedData = [
  {
    allPrimarySites: ["Bronchus and lung"],
    allTissuesOrOrgansOfOrigin: [
      "Lower lobe, lung",
      "Lung, NOS",
      "Main bronchus",
      "Middle lobe, lung",
      "Overlapping lesion of lung",
      "Upper lobe, lung",
    ],
    caseCount: 12143,
    fileCount: 97448,
    key: "Lung",
  },
  {
    allPrimarySites: ["Breast"],
    allTissuesOrOrgansOfOrigin: [
      "Axillary tail of breast",
      "Breast, NOS",
      "Central portion of breast",
      "Lower-inner quadrant of breast",
      "Lower-outer quadrant of breast",
      "Nipple",
      "Overlapping lesion of breast",
      "Upper-inner quadrant of breast",
      "Upper-outer quadrant of breast",
    ],
    caseCount: 9130,
    fileCount: 80479,
    key: "Breast",
  },
  {
    allPrimarySites: ["Colon", "Rectosigmoid junction", "Rectum"],
    allTissuesOrOrgansOfOrigin: [
      "Appendix",
      "Ascending colon",
      "Cecum",
      "Colon, NOS",
      "Descending colon",
      "Hepatic flexure of colon",
      "Overlapping lesion of colon",
      "Rectosigmoid junction",
      "Rectum, NOS",
      "Sigmoid colon",
      "Splenic flexure of colon",
      "Transverse colon",
    ],
    caseCount: 8108,
    fileCount: 50477,
    key: "Colorectal",
  },
  {
    allPrimarySites: ["Hematopoietic and reticuloendothelial systems"],
    allTissuesOrOrgansOfOrigin: [
      "Blood",
      "Bone marrow",
      "Hematopoietic system, NOS",
      "Reticuloendothelial system, NOS",
      "Spleen",
    ],
    caseCount: 9169,
    fileCount: 111762,
    key: "Bone Marrow and Blood",
  },
  {
    allPrimarySites: [
      "Meninges",
      "Peripheral nerves and autonomic nervous system",
      "Spinal cord, cranial nerves, and other parts of central nervous system",
    ],
    allTissuesOrOrgansOfOrigin: [
      "Acoustic nerve",
      "Autonomic nervous system, NOS",
      "Cauda equina",
      "Cerebral meninges",
      "Cranial nerve, NOS",
      "Meninges, NOS",
      "Nervous system, NOS",
      "Olfactory nerve",
      "Optic nerve",
      "Overlapping lesion of brain and central nervous system",
      "Overlapping lesion of peripheral nerves and autonomic nervous system",
      "Peripheral nerves and autonomic nervous system of abdomen",
      "Peripheral nerves and autonomic nervous system of head, face, and neck",
      "Peripheral nerves and autonomic nervous system of lower limb and hip",
      "Peripheral nerves and autonomic nervous system of pelvis",
      "Peripheral nerves and autonomic nervous system of thorax",
      "Peripheral nerves and autonomic nervous system of trunk, NOS",
      "Peripheral nerves and autonomic nervous system of upper limb and shoulder",
      "Spinal cord",
      "Spinal meninges",
    ],
    caseCount: 4239,
    fileCount: 9530,
    key: "Nervous System",
  },
  {
    allPrimarySites: ["Kidney"],
    allTissuesOrOrgansOfOrigin: ["Kidney, NOS"],
    caseCount: 3462,
    fileCount: 67965,
    key: "Kidney",
  },
  {
    allPrimarySites: ["Ovary"],
    allTissuesOrOrgansOfOrigin: ["Ovary"],
    caseCount: 3382,
    fileCount: 32132,
    key: "Ovary",
  },
  {
    allPrimarySites: ["Skin"],
    allTissuesOrOrgansOfOrigin: [
      "External ear",
      "Eyelid",
      "Overlapping lesion of skin",
      "Skin of lip, NOS",
      "Skin of lower limb and hip",
      "Skin of other and unspecified parts of face",
      "Skin of scalp and neck",
      "Skin of trunk",
      "Skin of upper limb and shoulder",
      "Skin, NOS",
    ],
    caseCount: 2886,
    fileCount: 27142,
    key: "Skin",
  },
  {
    allPrimarySites: ["Pancreas"],
    allTissuesOrOrgansOfOrigin: [
      "Body of pancreas",
      "Head of pancreas",
      "Islets of Langerhans",
      "Other specified parts of pancreas",
      "Overlapping lesion of pancreas",
      "Pancreas, NOS",
      "Pancreatic duct",
      "Tail of pancreas",
    ],
    caseCount: 2745,
    fileCount: 24836,
    key: "Pancreas",
  },
  {
    allPrimarySites: ["Prostate gland"],
    allTissuesOrOrgansOfOrigin: ["Prostate gland"],
    caseCount: 2392,
    fileCount: 30735,
    key: "Prostate",
  },
  {
    allPrimarySites: ["Thyroid gland"],
    allTissuesOrOrgansOfOrigin: ["Thyroid gland"],
    caseCount: 1880,
    fileCount: 38304,
    key: "Thyroid",
  },
  {
    allPrimarySites: ["Corpus uteri", "Uterus, NOS"],
    allTissuesOrOrgansOfOrigin: [
      "Corpus uteri",
      "Endometrium",
      "Fundus uteri",
      "Isthmus uteri",
      "Myometrium",
      "Overlapping lesion of corpus uteri",
      "Uterus, NOS",
    ],
    caseCount: 2664,
    fileCount: 37794,
    key: "Uterus",
  },
  {
    allPrimarySites: ["Liver and intrahepatic bile ducts"],
    allTissuesOrOrgansOfOrigin: ["intrahepatic bile duct", "Liver"],
    caseCount: 1607,
    fileCount: 23003,
    key: "Liver",
  },
  {
    allPrimarySites: ["Bladder"],
    allTissuesOrOrgansOfOrigin: [
      "Anterior wall of bladder",
      "Bladder neck",
      "Bladder, NOS",
      "Dome of bladder",
      "Lateral wall of bladder",
      "Overlapping lesion of bladder",
      "Posterior wall of bladder",
      "Trigone of bladder",
      "Urachus",
      "Ureteric orifice",
    ],
    caseCount: 1724,
    fileCount: 22886,
    key: "Bladder",
  },
  {
    allPrimarySites: ["Connective, subcutaneous and other soft tissues"],
    allTissuesOrOrgansOfOrigin: [
      "Connective, Subcutaneous and other soft tissues of abdomen",
      "Connective, Subcutaneous and other soft tissues of head, face, and neck",
      "Connective, Subcutaneous and other soft tissues of lower limb and hip",
      "Connective, Subcutaneous and other soft tissues of pelvis",
      "Connective, Subcutaneous and other soft tissues of thorax",
      "Connective, Subcutaneous and other soft tissues of trunk, NOS",
      "Connective, Subcutaneous and other soft tissues of upper limb and shoulder",
      "Connective, Subcutaneous and other soft tissues, NOS",
      "Overlapping lesion of connective, subcutaneous and other soft tissues",
    ],
    caseCount: 1577,
    fileCount: 9411,
    key: "Soft Tissue",
  },
  {
    allPrimarySites: ["Esophagus"],
    allTissuesOrOrgansOfOrigin: [
      "Abdominal esophagus",
      "Cervical esophagus",
      "Esophagus, NOS",
      "Lower third of esophagus",
      "Middle third of esophagus",
      "Overlapping lesion of esophagus",
      "Thoracic esophagus",
      "Upper third of esophagus",
    ],
    caseCount: 1400,
    fileCount: 12270,
    key: "Esophagus",
  },
  {
    allPrimarySites: ["Brain"],
    allTissuesOrOrgansOfOrigin: [
      "Brain stem",
      "Brain, NOS",
      "Cerebellum, NOS",
      "Cerebrum",
      "Frontal lobe",
      "Occipital lobe",
      "Overlapping lesion of brain",
      "Parietal lobe",
      "Temporal lobe",
      "Ventricle, NOS",
    ],
    caseCount: 1428,
    fileCount: 50915,
    key: "Brain",
  },
  {
    allPrimarySites: ["Small intestine", "Stomach"],
    allTissuesOrOrgansOfOrigin: [
      "Body of stomach",
      "Cardia, NOS",
      "Duodenum",
      "Fundus of stomach",
      "Gastric antrum",
      "Greater curvature of stomach, NOS",
      "Ileum",
      "Jejunum",
      "Lesser curvature of stomach, NOS",
      "Meckel diverticulum",
      "Overlapping lesion of small intestine",
      "Overlapping lesion of stomach",
      "Pylorus",
      "Small intestine, NOS",
      "Stomach, NOS",
    ],
    caseCount: 1623,
    fileCount: 25663,
    key: "Stomach",
  },
  {
    allPrimarySites: ["Cervix uteri"],
    allTissuesOrOrgansOfOrigin: [
      "Cervix uteri",
      "Endocervix",
      "Exocervix",
      "Overlapping lesion of cervix uteri",
    ],
    caseCount: 916,
    fileCount: 20568,
    key: "Cervix",
  },
  {
    allPrimarySites: [
      "Accessory sinuses",
      "Base of tongue",
      "Floor of mouth",
      "Gum",
      "Hypopharynx",
      "Larynx",
      "Lip",
      "Nasal cavity and middle ear",
      "Nasopharynx",
      "Oropharynx",
      "Other and ill-defined sites in lip, oral cavity and pharynx",
      "Other and ill-defined sites",
      "Other and unspecified major salivary glands",
      "Other and unspecified parts of mouth",
      "Other and unspecified parts of tongue",
      "Palate",
      "Parotid gland",
      "Pyriform sinus",
      "Tonsil",
      "Trachea",
    ],
    allTissuesOrOrgansOfOrigin: [
      "Accessory sinus, NOS",
      "Anterior 2/3 of tongue, NOS",
      "Anterior floor of mouth",
      "Anterior surface of epiglottis",
      "Anterior wall of nasopharynx",
      "Base of tongue, NOS",
      "Border of tongue",
      "Branchial cleft",
      "Cheek mucosa",
      "Commissure of lip",
      "Dorsal surface of tongue, NOS",
      "Ethmoid sinus",
      "External lip, NOS",
      "External lower lip",
      "External upper lip",
      "Floor of mouth, NOS",
      "Frontal sinus",
      "Glottis",
      "Gum, NOS",
      "Hard palate",
      "Head, face or neck, NOS",
      "Hypopharyngeal aspect of aryepiglottic fold",
      "Hypopharynx, NOS",
      "Laryngeal cartilage",
      "Larynx, NOS",
      "Lateral floor of mouth",
      "Lateral wall of nasopharynx",
      "Lateral wall of oropharynx",
      "Lingual tonsil",
      "Lip, NOS",
      "Lower gum",
      "Major salivary gland, NOS",
      "Maxillary sinus",
      "Middle ear",
      "Mouth, NOS",
      "Mucosa of lip, NOS",
      "Mucosa of lower lip",
      "Mucosa of upper lip",
      "Nasal cavity",
      "Nasopharynx, NOS",
      "Oropharynx, NOS",
      "Overlapping lesion of accessory sinuses",
      "Overlapping lesion of floor of mouth",
      "Overlapping lesion of hypopharynx",
      "Overlapping lesion of larynx",
      "Overlapping lesion of lip, oral cavity and pharynx",
      "Overlapping lesion of lip",
      "Overlapping lesion of major salivary glands",
      "Overlapping lesion of nasopharynx",
      "Overlapping lesion of other and unspecified parts of mouth",
      "Overlapping lesion of palate",
      "Overlapping lesion of tongue",
      "Overlapping lesion of tonsil",
      "Overlapping lesions of oropharynx",
      "Palate, NOS",
      "Parotid gland",
      "Pharynx, NOS",
      "Postcricoid region",
      "Posterior wall of hypopharynx",
      "Posterior wall of nasopharynx",
      "Posterior wall of oropharynx",
      "Pyriform sinus",
      "Retromolar area",
      "Soft palate, NOS",
      "Sphenoid sinus",
      "Subglottis",
      "Sublingual gland",
      "Submandibular gland",
      "Superior wall of nasopharynx",
      "Supraglottis",
      "Tongue, NOS",
      "Tonsil, NOS",
      "Tonsillar fossa",
      "Tonsillar pillar",
      "Trachea",
      "Upper Gum",
      "Uvula",
      "Vallecula",
      "Ventral surface of tongue, NOS",
      "Vestibule of mouth",
      "Waldeyer ring",
    ],
    caseCount: 2798,
    fileCount: 37271,
    key: "Head and Neck",
  },
  {
    allPrimarySites: [
      "Bones, joints and articular cartilage of limbs",
      "Bones, joints and articular cartilage of other and unspecified sites",
      "Other and ill-defined sites",
    ],
    allTissuesOrOrgansOfOrigin: [
      "Bone of limb, NOS",
      "Bone, NOS",
      "Bones of skull and face and associated joints",
      "Long bones of lower limb and associated joints",
      "Long bones of upper limb, scapula and associated joints",
      "Mandible",
      "Overlapping lesion of bones, joints and articular cartilage of limbs",
      "Overlapping lesion of bones, joints and articular cartilage",
      "Pelvic bones, sacrum, coccyx and associated joints",
      "Pelvis, NOS",
      "Rib, sternum, clavicle and associated joints",
      "Short bones of lower limb and associated joints",
      "Short bones of upper limb and associated joints",
      "Vertebral column",
    ],
    caseCount: 735,
    fileCount: 4140,
    key: "Bone",
  },
  {
    allPrimarySites: ["Adrenal gland"],
    allTissuesOrOrgansOfOrigin: [
      "Adrenal gland, NOS",
      "Cortex of adrenal gland",
      "Medulla of adrenal gland",
    ],
    caseCount: 851,
    fileCount: 14000,
    key: "Adrenal Gland",
  },
  {
    allPrimarySites: ["Heart, mediastinum, and pleura"],
    allTissuesOrOrgansOfOrigin: [
      "Anterior mediastinum",
      "Heart",
      "Mediastinum, NOS",
      "Overlapping lesion of heart, mediastinum and pleura",
      "Pleura, NOS",
      "Posterior mediastinum",
    ],
    caseCount: 706,
    fileCount: 6949,
    key: "Pleura",
  },
  {
    allPrimarySites: ["Testis"],
    allTissuesOrOrgansOfOrigin: [
      "Descended testis",
      "Testis, NOS",
      "Undescended testis",
    ],
    caseCount: 526,
    fileCount: 7256,
    key: "Testis",
  },
  {
    allPrimarySites: ["Lymph nodes"],
    allTissuesOrOrgansOfOrigin: [
      "Intra-abdominal lymph nodes",
      "Intrathoracic lymph nodes",
      "Lymph node, NOS",
      "Lymph nodes of axilla or arm",
      "Lymph nodes of head, face and neck",
      "Lymph nodes of inguinal region or leg",
      "Lymph nodes of multiple regions",
      "Pelvic lymph nodes",
    ],
    caseCount: 536,
    fileCount: 6816,
    key: "Lymph Nodes",
  },
  {
    allPrimarySites: ["Thymus"],
    allTissuesOrOrgansOfOrigin: ["Thymus"],
    caseCount: 306,
    fileCount: 4866,
    key: "Thymus",
  },
  {
    allPrimarySites: ["Other and unspecified parts of biliary tract"],
    allTissuesOrOrgansOfOrigin: [
      "Ampulla of Vater",
      "Biliary tract, NOS",
      "Extrahepatic bile duct",
      "Overlapping lesion of biliary tract",
    ],
    caseCount: 225,
    fileCount: 1106,
    key: "Bile Duct",
  },
  {
    allPrimarySites: ["Eye and adnexa"],
    allTissuesOrOrgansOfOrigin: [
      "Choroid",
      "Ciliary body",
      "Conjunctiva",
      "Cornea, NOS",
      "Eye, NOS",
      "Lacrimal gland",
      "Orbit, NOS",
      "Overlapping lesion of eye and adnexa",
      "Retina",
    ],
    caseCount: 223,
    fileCount: 4068,
    key: "Eye",
  },
];
