---
schemaVersion: 2.2.0
metadata:
  name: portal
  displayName: GDC Frontend Framework
  description: NodeJS application serving the portal for gdc.cancer.gov
  tags:
    - nodejs
  projectType: Node
  version: 0.0.1
components:
  - name: nodejs-web
    attributes:
      gl/inject-editor: true
    container:
      image: docker.osdc.io/ncigdc/amzn2023-builder:0.1587825349.65
      endpoints:
        - name: http
          targetPort: 3000
        - exposure: none
          name: debug
          targetPort: 9229
      env:
        - name: DEBUG_PORT
          value: '9229'
        - name: npm_config_registry
          value: https://nexus.osdc.io/repository/npm-all/
        - name: npm_config_proxy
          value: http://cloud-proxy-gdc.osdc.io:3128
        - name: npm_config_https_proxy
          value: http://cloud-proxy-gdc.osdc.io:3128
commands:
  - id: install-node
    exec:
      commandLine: nvm install 20.15.1
      workingDir: ${PROJECT_SOURCE}
      component: nodejs-web
  - id: run-app
    exec:
      commandLine: npm run start
      workingDir: ${PROJECT_SOURCE}
      component: nodejs-web

events:
  postStart:
    - install-node
