---
schemaVersion: 2.2.0
metadata:
  name: portal
  displayName: GDC Frontend Framework
  description: NodeJS application serving the portal for gdc.cancer.gov
  tags:
    - nodejs
  projectType: Node
  version: 0.0.1
components:
  - name: nodejs-web
    attributes:
      gl/inject-editor: true
    container:
      image: docker.osdc.io/ncigdc/amzn2023-builder:0.1587825349.69
      cpuLimit: "4"
      cpuRequest: "2"
      endpoints:
        - name: http
          targetPort: 3000
        - exposure: none
          name: debug
          targetPort: 9229
      env:
        - name: NODE_ENV
          value: development
        - name: DEBUG_PORT
          value: '9229'
        - name: npm_config_registry
          value: https://nexus.osdc.io/repository/npm-all/
        - name: npm_config_proxy
          value: http://cloud-proxy-gdc.osdc.io:3128
        - name: npm_config_https_proxy
          value: http://cloud-proxy-gdc.osdc.io:3128
        - name: npm_config_noproxy
          value: "*.osdc.io,*.datacommons.io,localhost,127.0.0.1"
commands:
  - id: install-node
    exec:
      commandLine: sudo dnf install nodejs20 nodejs20-npm -y
      component: nodejs-web
  - id: install-lerna
    exec:
      commandLine: sudo /usr/bin/npm install -g lerna@6
      component: nodejs-web
  - id: install-packages
    exec:
      commandLine: /usr/bin/npm ci --include=dev
      component: nodejs-web
  - id: lerna-core-compile-build
    exec:
      commandLine: /usr/bin/lerna run --scope @gff/core compile && /usr/bin/lerna run --scope @gff/core build
      component: nodejs-web
  - id: lerna-sapien-compile-build
    exec:
      commandLine: /usr/bin/lerna run --scope @nci-gdc/sapien compile && /usr/bin/lerna run --scope @nci-gdc/sapien build
      component: nodejs-web
  - id: lerna-portal-components-compile-build
    exec:
      commandLine: /usr/bin/lerna run --scope @gff/portal-components compile && /usr/bin/lerna run --scope @gff/portal-components build
      component: nodejs-web
  - id: lerna-portal-proto-build
    exec:
      commandLine: /usr/bin/lerna run --scope portal-proto build
      component: nodejs-web
  - id: run-app
    exec:
      commandLine: npm run start
      component: nodejs-web

events:
  postStart:
    - install-node
    - install-lerna
    - install-packages
    - lerna-core-compile-build
    - lerna-sapien-compile-build
    - lerna-portal-components-compile-build
    - lerna-portal-proto-build
