import { Diagnoses, FollowUps } from "@gff/core";

export const mockSingleDiagnoses: Diagnoses[] = [
  {
    days_to_recurrence: null,
    synchronous_malignancy: "No",
    morphology: "8140/3",
    submitter_id: "diagnosis-test",
    treatments: [
      {
        treatment_intent_type: "Neoadjuvant",
        days_to_treatment_start: null,
        treatment_id: "test",
        submitter_id: "test",
        therapeutic_agents: null,
        treatment_or_therapy: "no",
      },
      {
        treatment_intent_type: "Adjuvant",
        treatment_id: "test",
        submitter_id: "HCM-CSHL-0065-C20_treatment5",
        treatment_or_therapy: "no",
      },
      {
        treatment_intent_type: null,
        days_to_treatment_start: 48,
        treatment_id: "test",
        submitter_id: "HCM-CSHL-0065-C20_treatment4",
        therapeutic_agents: null,
        treatment_or_therapy: "yes",
      },
      {
        treatment_intent_type: "Adjuvant",
        days_to_treatment_start: null,
        treatment_id: "81c3c43d-8e0f-4095-a299-4c4bc185a63e",
        submitter_id: "HCM-CSHL-0065-C20_treatment2",
        therapeutic_agents: null,
        treatment_or_therapy: "no",
      },
    ],
    last_known_disease_status: null,
    tissue_or_organ_of_origin: "Colon, NOS",
    days_to_last_follow_up: null,
    age_at_diagnosis: 23111,
    primary_diagnosis: "Adenocarcinoma, NOS",
    classification_of_tumor: "metastasis",
    prior_malignancy: "no",
    diagnosis_id: "027c64ba-cd09-40e9-9495-12142f99aeb6",
    site_of_resection_or_biopsy: "Liver",
    days_to_last_known_disease_status: null,
    tumor_grade: "G2",
    progression_or_recurrence: null,
  },
];

export const mockMultipleDiagnoses: Diagnoses[] = [
  {
    days_to_recurrence: null,
    synchronous_malignancy: "No",
    morphology: "8140/3",
    submitter_id: "diag-test",
    treatments: [
      {
        treatment_intent_type: "Neoadjuvant",
        days_to_treatment_start: null,
        treatment_id: "test",
        submitter_id: "test",
        therapeutic_agents: null,
        treatment_or_therapy: "no",
      },
      {
        treatment_intent_type: "Adjuvant",
        treatment_id: "test",
        submitter_id: "HCM-CSHL-0065-C20_treatment5",
        treatment_or_therapy: "no",
      },
      {
        treatment_intent_type: null,
        days_to_treatment_start: 48,
        treatment_id: "test",
        submitter_id: "HCM-CSHL-0065-C20_treatment4",
        therapeutic_agents: null,
        treatment_or_therapy: "yes",
      },
    ],
    last_known_disease_status: null,
    tissue_or_organ_of_origin: "Colon, NOS",
    days_to_last_follow_up: null,
    age_at_diagnosis: 23111,
    primary_diagnosis: "Adenocarcinoma, NOS",
    classification_of_tumor: "metastasis",
    prior_malignancy: "no",
    diagnosis_id: "027c64ba-cd09-40e9-9495-12142f99aeb6",
    site_of_resection_or_biopsy: "Liver",
    days_to_last_known_disease_status: null,
    tumor_grade: "G2",
    progression_or_recurrence: null,
  },
  {
    days_to_recurrence: null,
    synchronous_malignancy: "No",
    morphology: "8140/3",
    submitter_id: "diag-test-1",
    treatments: [
      {
        treatment_intent_type: "Neoadjuvant",
        days_to_treatment_start: null,
        treatment_id: "test",
        submitter_id: "test",
        therapeutic_agents: null,
        treatment_or_therapy: "no",
      },
      {
        treatment_intent_type: "Adjuvant",
        treatment_id: "test",
        submitter_id: "HCM-CSHL-0065-C20_treatment5",
        treatment_or_therapy: "no",
      },
      {
        treatment_intent_type: null,
        days_to_treatment_start: 48,
        treatment_id: "test",
        submitter_id: "HCM-CSHL-0065-C20_treatment4",
        therapeutic_agents: null,
        treatment_or_therapy: "yes",
      },
      {
        treatment_intent_type: "Adjuvant",
        days_to_treatment_start: null,
        treatment_id: "81c3c43d-8e0f-4095-a299-4c4bc185a63e",
        submitter_id: "HCM-CSHL-0065-C20_treatment2",
        therapeutic_agents: null,
        treatment_or_therapy: "no",
      },
    ],
    last_known_disease_status: null,
    tissue_or_organ_of_origin: "Colon, NOS",
    days_to_last_follow_up: null,
    age_at_diagnosis: 23111,
    primary_diagnosis: "Adenocarcinoma, NOS",
    classification_of_tumor: "metastasis",
    prior_malignancy: "no",
    diagnosis_id: "027c64ba-cd09-40e9-9495-12142f99aeb6",
    site_of_resection_or_biopsy: "Liver",
    days_to_last_known_disease_status: null,
    tumor_grade: "G2",
    progression_or_recurrence: null,
  },
];

export const mockMultipleFollowUps: FollowUps[] = [
  {
    karnofsky_performance_status: null,
    follow_up_id: "21fa2463-9e93-4f42-9624-18a7e82953f0",
    progression_or_recurrence_anatomic_site: null,
    progression_or_recurrence_type: null,
    submitter_id: "follow-up-test",
    disease_response: null,
    days_to_follow_up: 186,
    ecog_performance_status: null,
    progression_or_recurrence: null,
    other_clinical_attributes: [
      {
        submitter_id: "HTMCP-01-16-00783_follow_up_oca",
        other_clinical_attribute_id: "ae2e4ee2-a878-438c-bf27-46006b2b0c90",
        weight: 60.3,
        height: 170,
        bmi: 20.9,
      },
    ],
  },
  {
    karnofsky_performance_status: null,
    follow_up_id: "2650764a-22df-4e21-a792-c60bb61cda92",
    progression_or_recurrence_anatomic_site: null,
    progression_or_recurrence_type: null,
    molecular_tests: [
      {
        test_units: null,
        variant_type: null,
        gene_symbol: "Not Reported",
        chromosome: null,
        aa_change: null,
        submitter_id: "HCM-CSHL-0065-C20_molecular_test",
        mismatch_repair_mutation: null,
        antigen: "CEA",
        biospecimen_type: null,
        test_value: 77,
        molecular_analysis_method: "Not Reported",
        second_gene_symbol: null,
        test_result: "Test Value Reported",
        laboratory_test: null,
        molecular_test_id: "17023afb-a7d2-430a-847b-f93468faf6be",
      },
      {
        test_units: null,
        variant_type: null,
        gene_symbol: "MSH2",
        chromosome: null,
        aa_change: null,
        submitter_id: "HCM-CSHL-0065-C20_molecular_test5",
        mismatch_repair_mutation: null,
        antigen: null,
        biospecimen_type: null,
        test_value: null,
        molecular_analysis_method: "IHC",
        second_gene_symbol: null,
        test_result: "Negative",
        laboratory_test: null,
        molecular_test_id: "1e1149f3-208f-4128-939e-1cd5816d2af1",
      },
    ],
    submitter_id: "follow-up-test-1",
    disease_response: null,
    days_to_follow_up: 0,
    ecog_performance_status: null,
    progression_or_recurrence: null,
  },
];

export const mockSingleFollowUps: FollowUps[] = [
  {
    karnofsky_performance_status: null,
    follow_up_id: "2650764a-22df-4e21-a792-c60bb61cda92",
    progression_or_recurrence_anatomic_site: null,
    progression_or_recurrence_type: null,
    molecular_tests: [
      {
        test_units: null,
        variant_type: null,
        gene_symbol: "Not Reported",
        chromosome: null,
        aa_change: null,
        submitter_id: "HCM-CSHL-0065-C20_molecular_test",
        mismatch_repair_mutation: null,
        antigen: "CEA",
        biospecimen_type: null,
        test_value: 77,
        molecular_analysis_method: "Not Reported",
        second_gene_symbol: null,
        test_result: "Test Value Reported",
        laboratory_test: null,
        molecular_test_id: "17023afb-a7d2-430a-847b-f93468faf6be",
      },
      {
        test_units: null,
        variant_type: null,
        gene_symbol: "MSH2",
        chromosome: null,
        aa_change: null,
        submitter_id: "HCM-CSHL-0065-C20_molecular_test5",
        mismatch_repair_mutation: null,
        antigen: null,
        biospecimen_type: null,
        test_value: null,
        molecular_analysis_method: "IHC",
        second_gene_symbol: null,
        test_result: "Negative",
        laboratory_test: null,
        molecular_test_id: "1e1149f3-208f-4128-939e-1cd5816d2af1",
      },
    ],
    submitter_id: "follow-up-test-1",
    disease_response: null,
    days_to_follow_up: 0,
    ecog_performance_status: null,
    progression_or_recurrence: null,
  },
];
