import { FiChevronDown as DownArrowCollapseIcon } from "react-icons/fi";
import { HiOutlinePencilSquare as PencilIcon } from "react-icons/hi2";
import { IoOptions as OptionsIcon } from "react-icons/io5";
import {
  MdOutlineApps as AppsIcon,
  MdArrowDropDown as ArrowDropDownIcon,
  MdShoppingCart as CartIcon,
  MdInfo as InfoIcon,
  MdKeyboardBackspace as LeftArrowIcon,
  MdOutlineLogin as LoginIcon,
  MdOutlineArrowBackIos as BackArrowIcon,
  MdOutlineArrowForwardIos as ForwardArrowIcon,
  MdKeyboardArrowDown as DownArrowIcon,
  MdKeyboardArrowUp as UpArrowIcon,
  MdOutlineArrowForward as RightArrowIcon,
  MdPlayArrow as PlayIcon,
  MdAdd as AddIcon,
  MdDelete as DeleteIcon,
  MdSave as SaveIcon,
  MdFileUpload as UploadIcon,
  MdDownload as DownloadIcon,
  MdClose as CloseIcon,
  MdAddCircle as MoreIcon,
  MdRemoveCircle as LessIcon,
  MdExpandLess as ExpandLessIcon,
  MdExpandMore as ExpandMoreIcon,
  MdSearch as SearchIcon,
  MdFlip as FlipIcon,
  MdLibraryAdd as AddFacetIcon,
  MdWarning as WarningTriangleIcon,
} from "react-icons/md";
import { VscFeedback as FeedbackIcon } from "react-icons/vsc";
import {
  FaCaretDown as DropdownIcon,
  FaUndo as UndoIcon,
  FaPlus as PlusIcon,
  FaMinus as MinusIcon,
} from "react-icons/fa";
import { RiErrorWarningFill as WarningMessageIcon } from "react-icons/ri";
import { FaCircle as CircleIcon } from "react-icons/fa";
import {
  PiCaretUpDownFill as SelectorIcon,
  PiCaretDownFill as SortDesIcon,
  PiCaretUpFill as SortAscIcon,
} from "react-icons/pi";
import { ImCalendar as CalendarIcon } from "react-icons/im";

export {
  CartIcon,
  AppsIcon,
  ArrowDropDownIcon,
  UpArrowIcon,
  BackArrowIcon,
  ForwardArrowIcon,
  DownArrowIcon,
  LeftArrowIcon,
  RightArrowIcon,
  InfoIcon,
  PlayIcon,
  DownArrowCollapseIcon,
  FeedbackIcon,
  PencilIcon,
  OptionsIcon,
  LoginIcon,
  DropdownIcon,
  UndoIcon,
  AddIcon,
  DeleteIcon,
  UploadIcon,
  SaveIcon,
  DownloadIcon,
  WarningMessageIcon,
  CloseIcon,
  CircleIcon,
  MoreIcon,
  LessIcon,
  ExpandLessIcon,
  ExpandMoreIcon,
  SearchIcon,
  FlipIcon,
  SelectorIcon,
  SortDesIcon,
  SortAscIcon,
  AddFacetIcon,
  WarningTriangleIcon,
  CalendarIcon,
  PlusIcon,
  MinusIcon,
};
