const LOADING_OVERLAY_Z_INDEX = 1;
const TABLE_HEADER_Z_INDEX = 10;
const MENU_Z_INDEX = 20;
const POPOVER_Z_INDEX = 30;
const TOOLTIP_Z_INDEX = 40;
const HEADER_Z_INDEX = 50;
const STICKY_HEADER_Z_INDEX = HEADER_Z_INDEX - 1;
const DRAWER_Z_INDEX = 60;
const MODAL_Z_INDEX = 70;

module.exports = {
  LOADING_OVERLAY_Z_INDEX,
  TABLE_HEADER_Z_INDEX,
  MENU_Z_INDEX,
  TOOLTIP_Z_INDEX,
  POPOVER_Z_INDEX,
  HEADER_Z_INDEX,
  STICKY_HEADER_Z_INDEX,
  DRAWER_Z_INDEX,
  MODAL_Z_INDEX,
};
