stages:
  - run_ui_tests

run_ui_tests:
  stage: run_ui_tests
  services:
    - docker:${DOCKER_VERSION}-dind
  tags:
    - dind
  image: docker:${DOCKER_VERSION}-dind
  script:
    - docker pull $DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME-holmes-py:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA}
    - docker run -v $(pwd):/app --name holmes-py --env APP_ENVIRONMENT=QA_INT --env browser="headless chrome" -e PATH="$PATH:/usr/local/bin" "$DOCKER_RELEASE_REGISTRY/ncigdc/$CI_PROJECT_NAME-holmes-py:$CI_COMMIT_REF_SLUG-${CI_COMMIT_SHORT_SHA}" gauge run ./holmes-py/specs/gdc_data_portal_v2/cohort_bar/general_cohort_functions.spec
    - docker cp holmes-py:/app/holmes-py/.gauge holmes-py/.gauge
    - docker cp holmes-py:/app/holmes-py/downloads holmes-py/downloads
    - docker cp holmes-py:/app/holmes-py/logs holmes-py/logs
    - docker cp holmes-py:/app/holmes-py/reports holmes-py/reports
  artifacts:
    when: always
    paths:
      - holmes-py/.gauge
      - holmes-py/downloads
      - holmes-py/logs
      - holmes-py/reports*
    expire_in: 3 months
