# /etc/nsswitch.conf
passwd:         files  # pragma: allowlist secret
group:          files
shadow:         files
gshadow:        files

# Only use files for host resolution, no DNS
hosts:          files [SUCCESS=return] files
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:           db files

netgroup:       nis
