# /etc/nsswitch.conf
passwd:         files  # pragma: allowlist secret
group:          files
shadow:         files
gshadow:        files

# Prefer /etc/hosts, then myhostname, then DNS (allow DNS for other lookups)
hosts:          files myhostname dns [NOTFOUND=return]
networks:       files

protocols:      db files
services:       db files
ethers:         db files
rpc:           db files

netgroup:       nis