version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - browser="headless edge"
    volumes:
      - .:/app
    command: gauge run ./specs/gdc_data_portal_v2/analysis_center/navigation.spec
