name: Pull Request Verify
on:
  pull_request:
    branch: 'develop'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3

      - name: Install Packages
        run: npm install
        
      - name: Run Prettier Check
        run: npm run format:check

      - name: Check for unit tests
        run: npm test

      - name: Compilation/Type Check for core
        run : |
          cd ${{github.workspace}}/packages/core
          npm run compile

      - name: Compilation/Type Check for portal-proto
        run : |
          cd ${{github.workspace}}/packages/portal-proto
          npm run compile       