name: Pull Request Verify
on:
  pull_request:
    branch: "develop"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: 16-alpine3.15

      - name: Install Packages
        run: |
          echo "Current Working Directory"
          pwd
          echo "List of Files"
          ls
          npm install

      - name: Compilation/Type Check for core
        run: |
          echo "Current Working Directory"
          pwd
          echo "List of files"
          ls
          echo " "
          cd ${{github.workspace}}/packages/core
          echo "List of files in ./packages/core"
          ls
          echo " "
          npm run build:clean

      - name: Compilation/Type Check for portal-proto
        run: |
          cd ${{github.workspace}}/packages/portal-proto
          npm run compile

      - name: Run lint check
        run: npm run lint

      - name: Run Prettier Check
        run: npm run format:check

      - name: Check for unit tests
        run: npm run test:all
